
networks:
  mixnet:

services:
  mixnode-1:
    container_name: server-1
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./keys/server-1-private.pem:/etc/mixnet/keys/private.pem:ro
      - ./keys/public:/etc/mixnet/keys/public:ro
      - ./certs/mixnode-1.crt:/etc/mixnet/certs/tls.crt:ro
      - ./certs/mixnode-1.key:/etc/mixnet/certs/tls.key:ro
      - ./certs/ca.crt:/etc/mixnet/certs/ca.crt:ro
    ports:
      - "40051:40050"
    networks:
      - mixnet

  client-1:
    container_name: client-1
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["--port", "50051"]
    stdin_open: true
    tty: true
    volumes:
      - ./keys/client-1-private.pem:/etc/mixnet/keys/private.pem:ro
      - ./keys/public:/etc/mixnet/keys/public:ro
      - ./certs/client-1.crt:/etc/mixnet/certs/tls.crt:ro
      - ./certs/client-1.key:/etc/mixnet/certs/tls.key:ro
      - ./certs/ca.crt:/etc/mixnet/certs/ca.crt:ro
    depends_on:
      - mixnode-1
    networks:
      - mixnet

  client-2:
    container_name: client-2
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["--port", "50052"]
    stdin_open: true
    tty: true
    volumes:
      - ./keys/client-2-private.pem:/etc/mixnet/keys/private.pem:ro
      - ./keys/public:/etc/mixnet/keys/public:ro
      - ./certs/client-2.crt:/etc/mixnet/certs/tls.crt:ro
      - ./certs/client-2.key:/etc/mixnet/certs/tls.key:ro
      - ./certs/ca.crt:/etc/mixnet/certs/ca.crt:ro
    depends_on:
      - mixnode-1
    networks:
      - mixnet

