
networks:
  mixnet:

services:
  client-1:
    container_name: client-1
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["-port", "50050", "-dest", "client-2:50050"]
    stdin_open: true
    tty: true
    volumes:
      - ./keys/client_1_private.pem:/etc/mixnet/keys/private.pem:ro
      - ./keys/public:/etc/mixnet/keys/public:ro
      - ./certs/client-1.crt:/etc/mixnet/certs/tls.crt:ro
      - ./certs/client-1.key:/etc/mixnet/certs/tls.key:ro
      - ./certs/ca.crt:/etc/mixnet/certs/ca.crt:ro
    networks:
      - mixnet

  client-2:
    container_name: client-2
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["-port", "50050", "-dest", "client-1:50050"]
    stdin_open: true
    tty: true
    volumes:
      - ./keys/client_2_private.pem:/etc/mixnet/keys/private.pem:ro
      - ./keys/public:/etc/mixnet/keys/public:ro
      - ./certs/client-2.crt:/etc/mixnet/certs/tls.crt:ro
      - ./certs/client-2.key:/etc/mixnet/certs/tls.key:ro
      - ./certs/ca.crt:/etc/mixnet/certs/ca.crt:ro
    networks:
      - mixnet

