package crypto

import (
	"crypto/tls"
	"crypto/x509"
	"errors"
	"os"

	"google.golang.org/grpc/credentials"
)

// LoadServerTLSCredentials loads TLS credentials for a gRPC server with mTLS.
// It verifies client certificates against the CA and presents its own leaf cert.
func LoadServerTLSCredentials(certFile, keyFile, caFile string) (credentials.TransportCredentials, error) {
	serverCert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, errors.New("LoadServerTLSCredentials: " + err.Error())
	}

	caCert, err := os.ReadFile(caFile)
	if err != nil {
		return nil, errors.New("LoadServerTLSCredentials: " + err.Error())
	}

	certPool := x509.NewCertPool()
	if !certPool.AppendCertsFromPEM(caCert) {
		return nil, errors.New("LoadServerTLSCredentials: failed to parse CA certificate")
	}

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{serverCert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
		ClientCAs:    certPool,
	}

	return credentials.NewTLS(tlsConfig), nil
}

// LoadClientTLSCredentials loads TLS credentials for a gRPC client with mTLS.
// It presents its own leaf cert and verifies the server against the CA.
func LoadClientTLSCredentials(certFile, keyFile, caFile string) (credentials.TransportCredentials, error) {
	clientCert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, errors.New("LoadClientTLSCredentials: " + err.Error())
	}

	caCert, err := os.ReadFile(caFile)
	if err != nil {
		return nil, errors.New("LoadClientTLSCredentials: " + err.Error())
	}

	certPool := x509.NewCertPool()
	if !certPool.AppendCertsFromPEM(caCert) {
		return nil, errors.New("LoadClientTLSCredentials: failed to parse CA certificate")
	}

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{clientCert},
		RootCAs:      certPool,
		// Certificates have no SANs (generated by simple openssl command),
		// so skip hostname verification but still verify the cert chain against the CA.
		InsecureSkipVerify:    true,
		VerifyPeerCertificate: verifyPeerCert(certPool),
	}

	return credentials.NewTLS(tlsConfig), nil
}

// verifyPeerCert returns a callback that verifies the peer's certificate chain
// against the CA pool, skipping hostname/SAN checks.
func verifyPeerCert(caPool *x509.CertPool) func(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
	return func(rawCerts [][]byte, _ [][]*x509.Certificate) error {
		if len(rawCerts) == 0 {
			return errors.New("no peer certificates presented")
		}

		cert, err := x509.ParseCertificate(rawCerts[0])
		if err != nil {
			return errors.New("failed to parse peer certificate: " + err.Error())
		}

		opts := x509.VerifyOptions{
			Roots: caPool,
		}

		if _, err := cert.Verify(opts); err != nil {
			return errors.New("failed to verify peer certificate: " + err.Error())
		}

		return nil
	}
}
